const String url='https://lavie.orangedigitalcenteregypt.com/api/v1/';
const String auth='auth/';
const String seeds='seeds';
const String tools='tools/';
const String plants='plants/';
const String products='products/';
const String USER='user/';
const String forums='forums';
String ACCESS_TOKEN = '';
